//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws.eng.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Projetoes = new HashSet<Projeto>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string Nome { get; set; }
        public string TelContato1 { get; set; }
        public string TelContato2 { get; set; }
        public string TelContato3 { get; set; }
        public string Email { get; set; }
        public string CpfCnpj { get; set; }
        public string Logradouro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string CodPostal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projeto> Projetoes { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
