//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws.eng.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjetoStatu
    {
        public System.DateTime DataStatus { get; set; }
        public int StatusID { get; set; }
        public long ProjetoID { get; set; }
        public long UsuarioID { get; set; }
        public string Observacao { get; set; }
    }
}
