//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws.eng.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjetoCliUsu
    {
        public int ID { get; set; }
        public int ClienteID { get; set; }
        public string TextoLivre { get; set; }
        public int PaisID { get; set; }
        public int LogradouroID { get; set; }
        public int AreaID { get; set; }
        public int PadraoID { get; set; }
        public int ProjetoID { get; set; }
        public Nullable<decimal> AreaPersonalizada { get; set; }
        public Nullable<System.DateTime> DataCad { get; set; }
        public Nullable<decimal> VlMetroQuadradoBase { get; set; }
        public int UsuarioID { get; set; }
        public System.Guid Token { get; set; }
    }
}
