//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws.eng.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjetoSolicitacaoIteracao
    {
        public long SolicitacaoID { get; set; }
        public System.DateTime Data { get; set; }
        public long UsuarioID { get; set; }
        public int EstadoID { get; set; }
        public string Texto { get; set; }
        public bool leituraRealizada { get; set; }
    }
}
