//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws.eng.dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicoHistorico
    {
        public long ID { get; set; }
        public long IdServico { get; set; }
        public long IdUsuario { get; set; }
        public int IdStatus { get; set; }
        public System.DateTime Data { get; set; }
        public string Historico { get; set; }
    }
}
